[package]
name = "snek_os"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bootloader = { git = "https://github.com/rust-osdev/bootloader" }
# snek_kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }

[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"

[workspace]
members = [
  "kernel",
  "crates/i8042"
]
