[package]
name = "snek_os"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bootloader = { git = "https://github.com/devsnek/bootloader.git", rev = "78fb1e58cb9e06548de20abeabfd11ebd75f2865" }

[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"

[workspace]
members = [
  "kernel",
  "crates/i8042",
  "crates/snalloc",
]
