[package]
name = "e9"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { version = "0.1", default-features = false, optional = true }
tracing-subscriber = { version = "0.3", default-features = false, optional = true }

[features]
tracing = ["dep:tracing", "dep:tracing-subscriber"]
