[package]
name = "snek_kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.9"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
crossbeam-queue = { version = "0.3", default-features = false, features = ["alloc"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
conquer-once = { version = "0.3", default-features = false }
noto-sans-mono-bitmap = "0.2"
mycelium-bitfield = { git = "https://github.com/hawkw/mycelium.git", rev = "f173c18b05543f3bf1abd7b5e3b2bfe32214e5d3" }
maitake = { git = "https://github.com/hawkw/mycelium.git", rev = "09c84f4e8171f60b1f0ab03627ba5040934dc3a7" }
rand_xoshiro = "0.6"
rand = { version = "0.8", default-features = false }
i8042 = { path = "../crates/i8042" }
pci-ids = "0.2"
pci_types = "0.3"
rustc-demangle = "0.1"
snalloc = { path = "../crates/snalloc" }
limine = "0.1"
e9 = { path = "../crates/e9" }
embedded-graphics = "0.8"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.14"
pic8259 = "0.10"
acpi = { git = "https://github.com/rust-osdev/acpi.git", rev = "e41036d3749a5a901e62cdf62011c735bf283e9c" }
os_units = "0.4"
x2apic = "0.4"
raw-cpuid = "10.6"
xmas-elf = "0.9"

[build-dependencies]
image = { version = "0.24", default-features = false, features = ["png"] }
